doctrine:
    dbal:
        default_connection: tool
        connections:
            tool:
                dbname:           toolssl_test
                user:             '%env(TOOL_DATABASE_USER)%'
                password:         '%env(TOOL_DATABASE_PASSWORD)%'
                host:             '%env(TOOL_DATABASE_HOST)%'
                server_version:   'mariadb-10.5.16'
                profiling_collect_backtrace: '%kernel.debug%'
                use_savepoints: true
    